---
title: ""
author: ""
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{rotating}
  - \usepackage{caption} 
  - \usepackage{float}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \captionsetup[table]{skip=10pt}
  - \setcounter{table}{0}
  - \renewcommand{\thetable}{C\arabic{table}}
  - \renewcommand{\thefigure}{C\arabic{figure}}
output: 
  pdf_document:
    fig_caption: TRUE
---

\lhead{Appendix C}

```{r setup, purl=FALSE, echo=FALSE}
draft = FALSE

library("knitr")
opts_chunk$set(echo     = draft, 
               results  = 'asis',
               message  = draft,
               warnings = draft,
               cache    = TRUE,
               fig.pos  = "b!",
               fig.height = 7)
```

```{r packages}
# library("default")
library("tidyverse")
library("xtable")

options(xtable.include.rownames = FALSE,
        xtable.comment = FALSE,
        xtable.caption.placement = "top")
# default(print.xtable) <- list(include.rownames = FALSE,
#                               comment = FALSE,
#                               caption.placement = "top")



library("kableExtra")
options(knitr.table.format = "latex")



library("HabitatRestoration")

max_length = function(sections) {
  max(as.integer(unlist(regmatches(sections, gregexpr("[[:digit:]]+", sections)))))
}

```

```{r sessionInfo, results='markup', eval=draft}
sessionInfo()
```

```{r palette, cache=TRUE}
ISU_primary_palette   <- c("#C8102E", "#F1BE48", "#524727", 
                           "#9B945F", "#CAC7A7")

ISU_secondary_palette <- c("#3E4827", "#76881D", "#A2A569",
                           "#003D4C", "#006BA6", "#7A99AC",
                           "#7C2529", "#9A3324", "#BE531C",
                           "#8B5B29", "#B9975B", "#EED484",
                           "#6E6259", "#707372", "#ACA39A")

####################################################################

month_col <- c("June"   = ISU_primary_palette[3], 
               "July"   = ISU_primary_palette[2],
               "August" = ISU_primary_palette[1])

class_col <- c("Forbs"             = ISU_secondary_palette[4],
               "Milkweed"          = ISU_secondary_palette[9],
               "Warm season grass" = ISU_secondary_palette[1],
               "Cool season grass" = ISU_secondary_palette[2],
               "Woody plants"      = ISU_secondary_palette[11],
               "Bare ground"       = ISU_secondary_palette[10])

class_linetype <- c("Forbs"        = "solid",
               "Milkweed"          = "solid",
               "Warm season grass" = "dotdash",
               "Cool season grass" = "dotted",
               "Woody plants"      = "dashed",
               "Bare ground"       = "dashed")

site_color <- c(ISU_secondary_palette, ISU_secondary_palette[1:6])
names(site_color) <- c("all1", "all2", "arm1", "arm2", "ber1", "ber3", "cre1",
                       "dun2", "dun3", "gro1", "gro2", "nkn1", "nkn2", "nor1",
                       "pio1", "pio2", "prd1", "prd2", "sie1", "sut2", "ver1")


```

\setlength{\tabcolsep}{3pt}


```{r sites}
sites <- unique(HabitatRestoration::transect %>% 
                 filter(grant=="ncig") %>%
                 filter(!(siteID %in% "sie1")) %>%
                 pull(siteID) %>% as.character())


# sites are ordered by region, then whether they were samples through 2019, and then alphabetically
# this is used in the mutate statement 15 lines down
sites <- bind_rows(tibble(region = "Northwest Iowa Plains",
                          site = c("prd1","prd2","sut2","all1","all2"),
                          success = c(T,T,T,F,F),
                          color = ISU_secondary_palette[1:5]),
                   tibble(region = "Des Moines Lobe",
                          site = c("dun2","dun3","pio1","pio2","nor1","ber1","ber3"),
                          success = c(T,T,T,T,T,F,F),
                          color = ISU_secondary_palette[1:7]),
                   tibble(region = "Southern Iowa Drift Plains",
                          site = c("arm1","arm2","nkn1","nkn2",
                                   "cre1","gro1","gro2","ver1"),
                          success = c(T,T,T,T,T,T,T,F),
                          color = ISU_secondary_palette[1:8])) %>%
  mutate(success = ifelse(success, "Yes","No"),
         success = factor(success, levels = c("Yes","No")))

site_linetype <- 2 - (sites$success == "Yes")
names(site_linetype) <- sites$site


regions = c("Northwest Iowa Plains","Des Moines Lobe","Southern Iowa Drift Plains")
```



\rhead{Robel Pole Survey}


```{r robel_censored, results='asis'}
HabitatRestoration::robel %>% 
  filter(censored != "not") %>%
  dplyr::mutate(height = ifelse(censored == "right", paste(">",height), height),
                height = paste(height, "cm"),
                date = as.character(date)) %>%
  dplyr::rename(direction = Direction,
                location = section,
                transect = transectID) %>%
  dplyr::select(-censored, -round) %>%
  
  xtable(caption = "The following Robel observations were above the maximum pole length of 160 cm. In the following analysis, these observations were treated as equal to the maximum pole height of 160 cm.") %>%
  print(include.rownames = FALSE,
        comment = FALSE,
        caption.placement = "top")

cat("\n\n")
```




```{r robel_data, dependson="sites"}
d <- HabitatRestoration::robel %>% 
  dplyr::left_join(HabitatRestoration::transect, by = "transectID") %>%
  dplyr::rename(site = siteID) %>%
  dplyr::mutate(site = as.character(site)) %>%
  filter(site %in% sites$site) %>%
  select(site, date, censored, height) %>%
  mutate(
    year = format(date, "%Y"),
    Month = factor(format(date, "%B"), levels = c("June","July","August")))

# stopifnot(all(d$censored == "not"))
```


```{r robel_monthly_data, dependson="robel_data"}
s <- d %>%
  group_by(year, Month, site) %>%
  summarize(height = mean(height)) %>%
  ungroup() %>%
  
  dplyr::left_join(sites, by = "site") %>%
  mutate(site = factor(site, levels = sites$site)) 
```



```{r robel_monthly_plot, dependson=c("palette"),fig.cap="Monthly average vegetation height (cm) from 2016 through 2019. "}
robel_monthly_plot <- function(s, r) {
  r = unique(s$region)
  
  ggplot(s, 
         aes(year, height, 
             linetype = Month, 
             group = Month,
             color = Month)) +
  geom_line() + 
  facet_wrap( ~ site) + 
  labs(x = "", y = "Height (cm)", 
       title=paste0("Monthly Average Vegetation Heights: ", r)) + 
  theme_bw() + 
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90)) +
  scale_color_manual(values = month_col)
}
```


```{r robel_monthly_table}
robel_monthly_table <- function(s) {
  r  <- unique(s$region)
  
  s %>%
    select(site, year, Month, height) %>%
    tidyr::pivot_wider(names_from = Month,
                       values_from = height) %>%
    select(site, year, June, July, August) %>%
    arrange(site, year) %>%
    
    xtable(digits = 0,
           caption = paste0("Monthly average vegetation height (cm): ", r)) %>%
    print(include.rownames = FALSE,
          comment = FALSE,
          caption.placement = "top")
}
```


```{r, robel_monthly, dependson=c("robel_monthly_data","robel_montly_plot","robel_monthly_table"), results='asis', fig.cap=paste("Robel monthly plots for",regions)}
for (r in regions) {
  robel_monthly_plot(s %>% filter(region == r)) %>% print
  cat("\n\n")
  robel_monthly_table(s %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}
```



```{r robel_yearly_data, dependson="robel_data"}
s_yearly <- d %>%
  group_by(year, site) %>%
  summarize(height = mean(height)) %>%
  ungroup() %>%
  
  left_join(sites, by="site") %>%
  mutate(site = factor(site, levels = sites$site))
```

```{r, robel_yearly_table}
robel_yearly_table <- function(s) {
  r  <- unique(s$region)
  
  s %>%
    select(site, year, height) %>%
    tidyr::pivot_wider(names_from = year,
                       values_from = height) %>%
    # select(site, year, June, July, August) %>%
    arrange(site) %>%
    
    xtable(digits = 0,
           caption = paste0("Yearly average vegetation height (cm): ", r)) %>%
    print(include.rownames = FALSE,
          comment = FALSE,
          caption.placement = "top")
}
```

```{r robel_yearly_plot, dependson=c("palette"),fig.cap="Yearly average vegetation height (cm) from 2016 through 2019."}
robel_yearly_plot <- function(s) {
  r = unique(s$region)
  
  ggplot(s, 
         aes(year, height, color = site, group = site, linetype = site)) +
    geom_line() + 
    # facet_grid(site ~ .) + 
    labs(x = "", 
         y = "Height (cm)",
         title = paste0("Yearly Average Vegetation Heights: ", r)) + 
    scale_color_manual(values = site_color) +
    scale_linetype_manual(values = site_linetype) +
    theme_bw() +
    theme(legend.position = "bottom") 
}
```

```{r robel_yearly, dependson=c("robel_yearly_data","robel_yearly_table","robel_yearly_plot"), fig.cap=paste("Robel yearly vegetation plots for", regions), fig.height=4}
for (r in regions) {
  robel_yearly_plot( s_yearly %>% filter(region == r)) %>% print
  cat("\n\n")
  robel_yearly_table(s_yearly %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}

```



```{r robel_write_plots, dependson=c("robel_monthly_plot","robel_yearly_plot"), eval=FALSE}
# ggsave(plot = g_monthly,
#        filename = "include/robel_monthly.png",
#        width = 6, height = 4)
# 
# ggsave(plot = g_yearly,
#        filename = "include/robel_yearly.png",
#        width = 6, height = 4)
```




\clearpage

\rhead{Daubenmire Survey}

```{r daubenmire_data, dependson="sites"}
d <- HabitatRestoration::cover %>% 
  dplyr::left_join(HabitatRestoration::transect, by = "transectID") %>%
  dplyr::rename(site = siteID) %>%
  filter(site %in% sites$site) %>%
  select(site, date, class, percentage) %>%
  mutate(
    year = format(date, "%Y"),
    month = factor(format(date, "%B"), levels = c("June","July","August"))) %>%
  filter(class %in% c("bare_ground","csg","forbs","milkweed","wsg","woody_species"))
```


```{r daubenmire_yearly_data, dependson="daubenmire_data"}
s <- d %>%
  group_by(year, site, class) %>%
  summarize(percentage = mean(percentage)) %>%
  ungroup() %>%
  
  left_join(sites, by = "site") %>%
  
  mutate(site = factor(site, levels = sites$site),
         
         class = recode(class,
                        bare_ground   = "Bare ground",
                        csg           = "Cool season grass",
                        wsg           = "Warm season grass",
                        milkweed      = "Milkweed",
                        woody_species = "Woody plants",
                        forbs         = "Forbs"),
         class = factor(class, 
                        levels = c("Bare ground",
                                   "Cool season grass",
                                   "Warm season grass",
                                   "Forbs",
                                   "Milkweed",
                                   "Woody plants")
                        )
         )
```


```{r daubenmire_yearly_table}
daubenmire_yearly_table <- function(s) {
  r = unique(s$region)
 
  s %>% 
    select(site, year, class, percentage) %>%
    dplyr::arrange(site, year, class) %>%
    pivot_wider(names_from = class,
                values_from = percentage) %>%
    arrange(site, year) %>%
    
    xtable(caption = paste0("Yearly average cover by class: ", r),
           digits = c(0,0,0,rep(1,6))) %>%
    print(include.rownames = FALSE,
          comment = FALSE,
          caption.placement = "top")
}
```


```{r daubenmire_yearly_plot, dependson="palette"}
daubenmire_yearly_plot <- function(s) {
  r = unique(s$region)
    
  ggplot(s, 
         aes(year, percentage, color=class, linetype = class, group = class)) +
  geom_line(size=1.1) + 
  facet_wrap( ~ site, scales = "free_y") +
  labs(x = "Year", y = "Average Cover", 
       title = paste0("Yearly Average Cover by Class: ", r)) +
  scale_color_manual(values = class_col) +
  scale_linetype_manual(values = class_linetype) +
  theme_bw() + 
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle=90),
        legend.key.width = unit(3, "line"))
}
```


```{r daubenmire_yearly_cumulative_plot, dependson=c("palette"), fig.height=8, fig.cap="Trends in yearly cumulative percent cover by vegetative class and bare soil from 2016 through 2019 (based on results for Daubenmire surveys; see Table 2 and Figure 3). "}
daubenmire_yearly_cumulative_plot <- function(s) {
  r = unique(s$region)
  
  ggplot(s %>%
           filter(region == r) %>%
           dplyr::mutate(class = factor(class, 
                                        levels = c("Milkweed","Forbs",
                                                   "Warm season grass",
                                                   "Cool season grass",
                                                   "Woody plants",
                                                   "Bare ground"))), 
         aes(year, percentage,
             fill = class, 
             # linetype = class, 
             group = class)) +
    geom_area(color=NA) + 
    facet_wrap(~ site) +
  labs(x = "Year", y = "Average Cover", 
       title = paste0("Cumulative Yearly Average Cover by Class: ", r)) +
  scale_fill_manual(values = class_col) +
  theme_bw() +
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle=90))
}
```



```{r daubenmire_yearly, dependson=c("daubenmire_yearly_data","daubenmire_yearly_table","daubenmire_yearly_plot","daubenmire_yearly_cumulative_plot"), fig.cap=paste("Trends in yearly cumulative percent cover by vegetative class and bare soil from 2016 through 2019 for",rep(regions, each=2))}
for (r in regions) {
  daubenmire_yearly_plot( s %>% filter(region == r)) %>% print
  cat("\n\n")
  daubenmire_yearly_cumulative_plot( s %>% filter(region == r)) %>% print
  cat("\n\n")
  daubenmire_yearly_table(s %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}
```




```{r daubenmire_write_plots, dependson=c("daubenmire_yearly_plot","daubenmire_yearly_cumulative_plot"), eval=FALSE}
# ggsave(filename = "include/daubenmire_yearly.png",
#        plot = g_yearly,
#        width = 6, 
#        height = 4)
# 
# ggsave(filename = "include/daubenmire_yearly_cumulative.png",
#        plot = g_yearly_by_class,
#        width = 6, 
#        height = 6)
```





\clearpage

\rhead{Nectar Plant Survey}

```{r nectar_data, dependson="sites"}
transect_length <- HabitatRestoration::nectar_surveys %>%
  
  dplyr::group_by(date, transectID) %>%
  dplyr::summarize(transect_length = max_length(section)) %>%
  dplyr::ungroup()


d <- HabitatRestoration::nectar %>% 
  dplyr::left_join(HabitatRestoration::transect %>% select(siteID, transectID),
                   by = "transectID") %>%
  dplyr::left_join(transect_length, by = c("date","transectID")) %>%
  
  dplyr::rename(
    site = siteID,
    common_name = `Nectar Plant Species`) %>%
  
  dplyr::left_join(HabitatRestoration::species %>% 
                     select(common_name, planted_non_planted, native_introduced_both), 
                   by="common_name") %>%
  # # removes white campion and yellow clover
  # dplyr::filter(!is.na(planted_non_planted)) %>%
  
  rename(native = native_introduced_both) %>%
  mutate(native = recode(native, 
                         native     = "Native (extant)",
                         both       = "Introduced/weed",
                         introduced = "Introduced/weed"),
         native = ifelse(planted_non_planted == "planted",
                         "Native (planted)", native),
         
         native = ifelse(common_name == "marestail",
                         "Introduced/weed", native))  %>%
  mutate(
    year  = format(date, "%Y"),
    month = factor(format(date, "%B"), levels = c("June","July","August"))) %>%
  
  select(year, month, site, transect_length, common_name, native, count) %>%
  
  filter(site %in% sites$site)
```


```{r nectar_monthly_data, dependson="nectar_data"}
s1 <- d %>% 
  group_by(year, month, site, transect_length) %>%
  summarize(total = sum(count)) %>%
  ungroup() %>%
  
  left_join(sites, by = "site") %>%
  
  mutate(native = "Combined",
         site = factor(site, levels = sites$site),
         total = total / transect_length * 100)


s2 <- d %>% 
  mutate(native = recode(native, 
                         `Native (planted)` = "Native",
                         `Native (extant)`  = "Native",
                         `Introduced/weed`  = "Introduced")) %>%
  
  group_by(year, site, month, native, transect_length) %>%
  summarize(total = sum(count)) %>%
  ungroup() %>%
  
  dplyr::left_join(sites, by = "site") %>%
  
  mutate(site = factor(site, levels = sites$site),
         total = total / transect_length * 100) 

# %>%
# 
#   # Hack to add appropriate zeros
#   bind_rows(tibble(site = rep(c("Boyd 1","Boyd 2"), each = 4),
#                    year = rep(c(2016,2016,2016,2017),2),
#                    native = rep("Native",8),
#                    month  = rep(c("June","July","August","June"),2),
#                    total  = rep(0,8)) %>%
#               mutate(month = factor(month, levels=c("June","July","August"))))
  

s_both <- bind_rows(s1,s2) %>%
  mutate(native = factor(native, levels = c("Combined",
                                            "Native",
                                            "Introduced"))) 
```


```{r nectar_monthly_table}
nectar_monthly_table <- function(s) {
  r = unique(s$region)
  
  s %>% 
    select(site, year, month, total, native) %>%
    unite("year_month", year, month, sep="_") %>%
    pivot_wider(names_from = year_month,
                values_from = total) %>%
    arrange(site, native) %>%
    
    xtable(digits = 0,
           caption = paste0("Total Monthly Inflorescence: ", r),
           align = "lll|rrr|rrr|rrr|rrr|") %>%
    print(include.rownames = FALSE,
          comment = FALSE,
          caption.placement = "top",
          rotate.colnames = TRUE)
}
```



```{r nectar_monthly_plot, dependson="palette",fig.height=8}
nectar_monthly_plot <- function(s) {
  r = unique(s$region)
  
  ggplot(s, 
         aes(year, total, 
             linetype = month, group = month, color = month)) +
    geom_line() + 
    facet_grid(site ~ native, scales="free_y") + 
    labs(x = "Year", y = "Total Inflorescence (count/100m2)", 
         title = paste0("Total Monthly Inflorescence: ", r),
         linetype = "Month", color = "Month") +
  # scale_y_log10() +
  scale_color_manual(values = month_col) + 
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=90))
}
```


```{r nectar_monthly, dependson=c("nectar_monthly_data","nectar_monthly_plot","nectar_monthly_table"), fig.cap=paste("Plots of monthly average native forbs, extant native forbs, introduced/weed species, and combined (native and introduced/weed) nectar plant inflorescence density by year for each site in", regions)}
for (r in regions) {
  nectar_monthly_plot( s_both %>% filter(region == r)) %>% print
  cat("\n\n")
  nectar_monthly_table(s_both %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}

```



```{r, nectar_write_plots, dependson="nectar_monthly_plot", eval=FALSE}
# ggsave(file = "include/nectar_monthly.png",
#        plot = g,
#        width = 6, 
#        height = 4)
```



```{r, nectar_by_species, dependson="nectar_data"}
s <- d %>% 
  # filter(`Nectar Plant Species` != "white clover") %>%
  group_by(year, site, month, common_name, native) %>%
  summarize(total = sum(count)) %>%
  left_join(sites, by = "site") %>%
  ungroup() %>%
  mutate(site = factor(site, levels = sites$site))
```  


```{r nectar_ratio, dependson="nectar_by_species", eval=TRUE}
# ggplot(s, aes(year, total, 
#               color = common_name,
#               linetype = native,
#               group = common_name)) +
#   geom_line() + 
#   facet_grid(site ~ month) + 
#   labs(x = "Year", y = "Inflorescence", linetype = "Species") +
#   scale_y_log10() + 
#   theme_bw() + 
#   theme(legend.position = "bottom")

ss <- s %>%
  group_by(year, site, common_name, native) %>%
  summarize(total = sum(total)) %>%
  spread(year, total, fill = 0) %>%
  mutate(log_ratio = log10(`2019`+1) - log10(`2018`+1)) %>% 
  # arrange(native, log_ratio, common_name, site) %>%
  select(site, common_name, native, log_ratio) %>%
  spread(site, log_ratio, fill=NA) 

# %>%
#   
#   # Manually filter species with only 1 site with data and
#   # ratio is close to zero
#   filter(!(common_name %in% c("blue wild indigo","canada goldenrod",
#                               "common evening primrose","prostrate vervain",
#                               "hawkweed","smartweed","common milkweed")))

# ss %>% write_csv("include/nectar_ratio.csv")
```


```{r, nectar_ratio_by_mean_ratio, dependson="nectar_ratio", eval=TRUE}
# ss %>%
#   arrange(
#     -rowMeans(cbind(all1, all2, arm1, arm2, ber1, ber3, cre1, dun2, dun3, 
#                     gro1, gro2, nkn1, nkn2, nor1, pio1, pio2, prd1, prd2, sie1, 
#                     sut2, ver1), na.rm=TRUE),
#     common_name) %>%
#   select(native, common_name, everything()) %>%
#   rename(`Common name` = common_name,
#          `Native status` = native) %>%
#   
#   xtable(
#     caption = "Logarithm of the ratio of inflorescence counts (+1) from 2019  to 2018 arranged by average across sites,
#     thus negative values indicate a reduction while positive values indicate an increase. Missing values had no observations at that site for either 2018 or 2019.",
#     align = "lll|rrrr",
#     digits = 1
#   ) %>%
#   
#   print(
#     include.rownames = FALSE,
#     caption.placement = "top",
#     comment = FALSE
#   )
```

```{r, nectar_ratio_by_native, dependson="nectar_ratio", eval=TRUE}
n_native  = sum(grepl("Native",  ss$native))
n_planted = sum(grepl("planted", ss$native))

# ss %>%
#   mutate(native = factor(native, levels = c("Native (planted)",
#                                             "Native (extant)",
#                                             "Introduced/weed"))) %>%
#   arrange(
#     native,
#     -rowMeans(cbind(all1, all2, arm1, arm2, ber1, ber3, cre1, dun2, dun3, 
#                     gro1, gro2, nkn1, nkn2, nor1, pio1, pio2, prd1, prd2, sie1,
#                     sut2, ver1), na.rm=TRUE),
#     common_name) %>%
#   select(-native) %>%
#   rename(`Common name` = common_name) %>%
#   
#   xtable(
#     caption = "Logarithm of the ratio of inflorescence counts (+1) from 2019 over 2018 arranged by mean ratio across sites within each native grouping: native above double line and planted above single line. Negative values indicate a reduction while positive values indicate an increase. Missing values had no observations at that site for either 2018 or 2019.",
#     align = "ll|rrrr",
#     digits = 1
#   ) %>%
#   
#   print(
#     include.rownames = FALSE,
#     caption.placement = "top",
#     hline.after = c(-1,0,n_planted,n_native,n_native,nrow(ss)),
#     comment = FALSE
#   )
```




```{r, nectar_write_table, dependson="nectar_by_species"}
ss <- s %>%
  group_by(year, site, common_name, native) %>%
  summarize(density = mean(total)) %>%
  mutate(native = factor(native, levels=c("Native (planted)","Native (extant)",
                                          "Introduced/weed"))) %>%
  
  unite("site_year", site, year, sep="@") %>%
  spread(site_year, density, fill = NA) %>%
  arrange(native, common_name) %>%
  rename(`Plant name` = "common_name")

n_native  = sum(grepl("Native",  ss$native))
n_planted = sum(grepl("planted", ss$native))
ss$native <- NULL

# Fix column names and create additional row
nc <- ncol(ss)
tmp <- data.frame(nms = names(ss)[-1]) %>%
  tidyr::separate(nms, into=c("row1", "row2"), sep="@")
names(ss)[-1] <- tmp$row2
new_row <- paste(" & \\multicolumn{4}{c|}{",unique(tmp$row1),"}", 
                 collapse="")
new_row <- gsub("_", " ", new_row)
new_row <- paste(new_row, "\\\\", collapse=" ")

# tab <- ss %>%
#   xtable(
#     digits = 0,
#     align = paste("rl|",paste(rep("rrrr|",floor(nc/4)),collapse=""),sep="",collapse=""),
#     caption="Average inflourescence (count/100m2) across all rounds by plant classification: native (planted or extant) above double line, planted above single line, and introduced/weed below double line.",
#     label = "t:nectar") %>%
#   print(
#     # file = "include/nectar_yearly.tex",
#     include.rownames = FALSE, 
#     # NA.string="na",
#     add.to.row = list(pos = list(-1), 
#                       command = new_row),
#     caption.placement = "top",
#     size="\\small",
#     # floating.environment = "sidewaystable",
#     hline.after = c(-1,0,n_planted,n_native,n_native,nrow(ss)),
#     comment = FALSE
#   ) 
```



```{r nectar_heatmap_data, dependson="nectar_by_species",fig.height=8,fig.cap="Heat map of average nectar plant inflorescence density; species sorted by average presence."}
# Determine sort order 
abundance <- s %>%
  group_by(common_name) %>%
  summarize(total = sum(total)) %>%
  arrange(total)

ss <- s %>%
  mutate(common_name = factor(common_name,
                              levels = abundance$common_name),
         native = factor(native, 
                         levels=c("Native (planted)",
                                  "Native (extant)",
                                  "Introduced/weed")))
```



```{r nectar_heatmap_table}
nectar_heatmap_table <- function(s) {
  # This is going to be a huge table
  r = unique(s$region)
  
  s %>% 
    select(site, year, month, common_name, native, total) %>%
    pivot_wider(names_from = site) # unfinished
}
```


```{r nectar_heatmap_plot, dependson=c("palette")}
nectar_heatmap_plot <- function(s) {
  r = unique(s$region)
  
  ggplot(s %>%
           filter(total > 0.1), 
         aes(year, common_name, fill = total)) +
    geom_tile() + 
    # scale_y_discrete(limits = rev(levels(as.factor(s$common_name)))) +
    facet_grid(native ~ site, scales="free_y", space="free_y") + 
    scale_fill_gradient(low = "cornsilk", high = "darkgreen", trans = "log") +
    theme_bw() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle=90),
          axis.text.y = element_text(hjust=0)) +
    labs(x = "", y = "", title = paste0(r," (< 0.1 observations removed)")) 
}
```

```{r nectar_heatmap, dependson=c("nectar_heatmap_data","nectar_heatmap_plot"), fig.cap=paste("Heatmaps of inflorescent data in", regions)}
for (r in regions) {
  nectar_heatmap_plot( ss %>% filter(region == r)) %>% print
  cat("\n\n")
  # nectar_monthly_table(s_both %>% filter(region == r))
  cat('\\clearpage')
  cat("\n\n")
}
```

```{r, nectar_write_heatmap, dependson="nectar_heatmap", eval=FALSE}
# ggsave(file = "include/nectar_heatmap.png",
#        plot = g,
#        width = 6, 
#        height = 8)
```


\clearpage

\rhead{Monarch Survey}

```{r monarch_data, dependson="sites"}
d <- HabitatRestoration::monarch %>% 
  dplyr::left_join(transect %>% select(siteID,transectID), by="transectID") %>%
  filter(siteID %in% sites$site,
         type != "palmer amaranth") %>%
  rename(site = siteID) %>%
  mutate(
    year = format(date, "%Y"),
    month = factor(format(date, "%B"), levels = c("June","July","August"))) %>%
  
  group_by(year, site, type, milkweed) %>%
  summarize(total = sum(count)) %>%
  ungroup() %>%
  
  # Create total columns
  mutate(type = recode(type, extra = "total", instar = "larvae")) %>%
  unite("type_milkweed", type, milkweed) %>%
  spread(type_milkweed, total, fill = 0) %>%
  mutate(total_NA = survey_NA + total_NA,
         eggs_NA   = eggs_NA   + eggs_common   + eggs_butterfly   + eggs_swamp,
         ramets_NA = ramets_NA + ramets_common + ramets_butterfly + ramets_swamp,
         larvae_NA = larvae_NA + larvae_common + larvae_butterfly + larvae_swamp) %>%
  gather("type_milkweed", "count", -year, -site) %>%
  separate(type_milkweed, c("type","milkweed"), sep="_") %>%
  
  mutate(
    milkweed = ifelse(type == "survey", "survey", milkweed),
    milkweed = ifelse(type == "total", "", milkweed),
    # milkweed = tools::toTitleCase(milkweed),
    milkweed = factor(milkweed, 
                      levels = c("butterfly","common","swamp","survey","total")),
    
    type = recode(type, survey = "adults", total = "adults"),
    type = tools::toTitleCase(type)) %>%
  unite("Monarch", type, milkweed, sep=", ") %>%
  mutate(
    Monarch = gsub(", NA", ", total", Monarch),
    Monarch = factor(Monarch, 
                     levels = c("Adults, survey", "Adults, total",
                                "Eggs, butterfly", "Eggs, common", "Eggs, swamp", "Eggs, total",
                                "Larvae, butterfly", "Larvae, common", "Larvae, swamp", "Larvae, total",
                                "Ramets, butterfly", "Ramets, common", "Ramets, swamp", "Ramets, total"))) %>%
  ungroup() %>%
  left_join(sites, by="site") %>%
  mutate(site = factor(site, levels = sites$site)) %>%
  arrange(site, year)
```



```{r monarch_table}
monarch_table <- function(s) {
  r = unique(s$region)
  
  s %>% 
    select(year, site, Monarch, count) %>%
    tidyr::unite("site_year", site, year, sep="_") %>%
    pivot_wider(names_from = site_year,
                values_from = count) %>%
    arrange(Monarch)  %>%
    
    xtable(digits = 0, 
           caption = paste0("Yearly monarch stages and milkweed ramets: ", r)) %>%
    
    print(comment = FALSE,
          include.rownames=FALSE,
          caption.placement = "top",
          rotate.colnames = TRUE,
          floating.environment = "sidewaystable",
          hline.after = c(-1,0,2,6,10,14))
}
```



```{r monarch_plot, dependson="palette"}
monarch_plot <- function(s) {
  r = unique(s$region)
  
  ggplot(s %>%
           mutate(Monarch = sub(", total","",Monarch)) %>%
           filter(Monarch %in% c("Adults","Eggs","Larvae","Ramets")), 
         aes(year, count, group = Monarch)) +
    # geom_point() + 
    geom_line() + 
    facet_grid(Monarch ~ site, scales="free_y") + 
    labs(x = "Year", y = "Count",
         title = paste0("Yearly Monarch Stages and Milkweed Ramets: ", r)) +
    # scale_y_log10() + 
    theme_bw() +
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle=90))
}
```



```{r monarch_yearly, dependson=c("monarch_data","monarch_table","monarch_plot"), fig.cap=paste("Yearly observed monarch eggs, larvae, and adults during a site visit and total number of milkweed ramets (butterfly, common and swamp combined) for sites in", regions)}
for (r in regions) {
  monarch_plot( d %>% filter(region == r)) %>% print
  cat("\n\n")
  monarch_table(d %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}
```

```{r write_monarch_plots, dependson="monarch_plot", eval=FALSE}
# ggsave(file = "include/monarch_yearly.png",
#        plot = g,
#        width = 6, 
#        height = 4)
```

