---
title: ""
author: ""
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{rotating}
  - \usepackage{caption} 
  - \usepackage{float}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \captionsetup[table]{skip=10pt}
  - \setcounter{table}{0}
  - \renewcommand{\thetable}{C\arabic{table}}
  - \renewcommand{\thefigure}{C\arabic{figure}}
output: 
  pdf_document:
    fig_caption: TRUE
---

\lhead{Appendix C}

```{r setup, purl=FALSE, echo=FALSE}
draft = FALSE

library("knitr")
opts_chunk$set(echo     = draft, 
               results  = 'asis',
               message  = draft,
               warnings = draft,
               cache    = FALSE,
               fig.pos  = "b!",
               fig.height = 7)
```

```{r packages}
library("drake")
loadd(palette)
loadd(ncig_sites)
loadd(robel_monthly)
loadd(robel_yearly)
loadd(cover_yearly)
loadd(nectar_monthly)
loadd(nectar_by_species)
loadd(monarch)
```

```{r sessionInfo, results='markup', eval=draft}
sessionInfo()
```

\setlength{\tabcolsep}{3pt}


```{r sites}
linetype <- 2 - (ncig_sites$success == "Yes")
names(linetype) <- ncig_sites$site

color <- c(ISU_secondary_palette, ISU_secondary_palette[1:6])
names(color) <- c("all1", "all2", "arm1", "arm2", "ber1", "ber3", "cre1",
                       "dun2", "dun3", "gro1", "gro2", "nkn1", "nkn2", "nor1",
                       "pio1", "pio2", "prd1", "prd2", "sie1", "sut2", "ver1")

regions = unique(ncig_sites$region)

filter_ncig <- function(d) {
  d %>%
    dplyr::left_join(ncig_sites, by = "site") %>%
    mutate(site = factor(site, levels = ncig_sites$site)) %>%
    filter( !is.na(region) )
}
```

\rhead{Robel Pole Survey}


```{r robel_monthly, results='asis', fig.cap=paste("Robel monthly plots for",regions)}
s = filter_ncig(robel_monthly)

for (r in regions) {
  robel_monthly_plot(s %>% filter(region == r), palette) %>% print
  cat("\n\n")
  robel_monthly_table(s %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}
```

```{r robel_yearly, fig.cap=paste("Robel yearly vegetation plots for", regions), fig.height=4}
s = filter_ncig(robel_yearly)

for (r in regions) {
  robel_yearly_plot( s %>% filter(region == r), 
                     color = color, linetype = linetype) %>% print
  cat("\n\n")
  robel_yearly_table(s %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}
```



\clearpage

\rhead{Daubenmire Survey}

```{r daubenmire_yearly, dependson=c("daubenmire_yearly_data","daubenmire_yearly_table","daubenmire_yearly_plot","daubenmire_yearly_cumulative_plot"), fig.cap=paste("Trends in yearly cumulative percent cover by vegetative class and bare soil from 2016 through 2019 for", rep(regions, each=2))}
s = filter_ncig(cover_yearly)

for (r in regions) {
  cover_yearly_plot( s %>% filter(region == r), palette) %>% print
  cat("\n\n")
  cover_yearly_cumulative_plot( s %>% filter(region == r), palette) %>% print
  cat("\n\n")
  cover_yearly_table(s %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}
```




\clearpage

\rhead{Nectar Plant Survey}


```{r nectar_monthly, fig.cap=paste("Plots of monthly average native forbs, extant native forbs, introduced/weed species, and combined (native and introduced/weed) nectar plant inflorescence density by year for each site in", regions)}
s = filter_ncig(nectar_monthly)

for (r in regions) {
  nectar_monthly_plot( s %>% filter(region == r), palette) %>% print
  cat("\n\n")
  nectar_monthly_table(s %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}
```



```{r nectar_heatmap, dependson=c("nectar_heatmap_data","nectar_heatmap_plot"), fig.cap=paste("Heatmaps of inflorescent data in", regions)}
s = filter_ncig(nectar_by_species)

for (r in regions) {
  nectar_heatmap_plot( s %>% filter(region == r)) %>% print
  cat("\n\n")
  # nectar_monthly_table(s_both %>% filter(region == r))
  cat('\\clearpage')
  cat("\n\n")
}
```



\clearpage

\rhead{Monarch Survey}

```{r monarch_yearly, dependson=c("monarch_data","monarch_table","monarch_plot"), fig.cap=paste("Yearly observed monarch eggs, larvae, and adults during a site visit and total number of milkweed ramets (butterfly, common and swamp combined) for sites in", regions)}
s = filter_ncig(monarch)

for (r in regions) {
  monarch_plot( s %>% filter(region == r)) %>% print
  cat("\n\n")
  monarch_table(s %>% filter(region == r))
  cat("\n\n")
  cat('\\clearpage')
  cat("\n\n")
}
```

