---
title: ""
author: ""
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{rotating}
  - \usepackage{caption} 
  - \usepackage{float}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \captionsetup[table]{skip=10pt}
output: 
  pdf_document:
    fig_caption: TRUE
---

```{r setup, purl=FALSE, echo=FALSE}
draft = FALSE

library("knitr")
opts_chunk$set(echo     = draft, 
               results  = 'asis',
               message  = draft,
               warnings = draft,
               cache    = TRUE,
               fig.pos  = "b!")
```

```{r packages}
library("tidyverse")
library("ISUmonarch")
library("xtable")
```

```{r sessionInfo, results='markup', eval=draft}
sessionInfo()
```

```{r palette, cache=TRUE}
ISU_primary_palette   <- c("#C8102E", "#F1BE48", "#524727", 
                           "#9B945F", "#CAC7A7")

ISU_secondary_palette <- c("#3E4827", "#76881D", "#A2A569",
                           "#003D4C", "#006BA6", "#7A99AC",
                           "#7C2529", "#9A3324", "#BE531C",
                           "#8B5B29", "#B9975B", "#EED484",
                           "#6E6259", "#707372", "#ACA39A")

####################################################################

month_col <- c("June"   = ISU_primary_palette[3], 
               "July"   = ISU_primary_palette[2],
               "August" = ISU_primary_palette[1])

class_col <- c("Forbs"             = ISU_secondary_palette[4],
               "Milkweed"          = ISU_secondary_palette[9],
               "Warm season grass" = ISU_secondary_palette[1],
               "Cool season grass" = ISU_secondary_palette[2],
               "Woody plants"      = ISU_secondary_palette[11],
               "Bare ground"       = ISU_secondary_palette[10])

class_linetype <- c("Forbs"        = "solid",
               "Milkweed"          = "solid",
               "Warm season grass" = "dotted",
               "Cool season grass" = "dotted",
               "Woody plants"      = "dashed",
               "Bare ground"       = "dashed")

site_color <- c("Boyd 1" = ISU_primary_palette[4],
                "Boyd 2" = ISU_primary_palette[5],
                "Crawfordsville" = ISU_primary_palette[3],
                "Uthe 3" = ISU_primary_palette[1])
```

\setlength{\tabcolsep}{3pt}


```{r sites}
sites <- unique(ISUmonarch::transect %>% 
                 filter(grant=="iacig") %>%
                 filter(siteID %in% c("byd1","byd2","cra1","uth3")) %>%
                 pull(siteID) %>% as.character())
```



\lhead{Robel Pole Survey}

```{r robel_data, dependson="sites"}
d <- robel %>% 
  filter(siteID %in% sites) %>%
  select(siteID, year, month, height, censored) %>%
  rename(site = siteID) %>%
  mutate(Month = recode(month, `6` = "June", `7` = "July", `8` = "August"),
         Month = factor(Month, levels = c("June","July","August")),
         
         site = recode(site, 
                         byd1 = "Boyd 1", 
                         byd2 = "Boyd 2",
                         cra1 = "Crawfordsville",
                         uth3 = "Uthe 3")) 

stopifnot(all(d$censored == "not"))
```


```{r robel_monthly, dependson="robel_data"}
s <- d %>%
  group_by(year, site, Month) %>%
  summarize(height = mean(height))
```

```{r, robel_monthly_table, dependson=c("robel_monthly")}
ss <- s %>%
  unite("site_year", site, year, sep="@") %>%
  spread(site_year, height, fill = NA) 

# Fix column names and create additional row
nc <- ncol(ss)
tmp <- data.frame(nms = names(ss)[-1]) %>%
  tidyr::separate(nms, into=c("row1", "row2"), sep="@")
names(ss)[-1] <- tmp$row2
new_row <- paste(" & \\multicolumn{4}{c|}{",unique(tmp$row1),"}", 
                 collapse="")
new_row <- gsub("_", " ", new_row)
new_row <- paste(new_row, "\\\\", collapse=" ")


# Write table to file
tab <- ss %>%
  xtable(
    digits = 0,
    align = paste("rl|",paste(rep("rrrr|",floor(nc/4)),collapse=""),sep="",collapse=""),
    caption="Monthly average vegetation height (cm) from 2016 through 2019.",
    label = "t:daubenmire_monthly") %>%
  print(
    # file = "include/daubenmire_monthly.tex",
    include.rownames = FALSE, 
    # NA.string="na",
    add.to.row = list(pos = list(-1), 
                      command = new_row),
    caption.placement = "top",
    size="\\small",
    # floating.environment = "sidewaystable",
    hline.after = c(-1,0,3),
    comment = FALSE
    ) 
```

```{r, robel_monthly_plot, dependson=c("robel_monthly","palette"),fig.height=4,fig.cap="Monthly average vegetation height (cm) from 2016 through 2019. "}
g_monthly <- ggplot(s, aes(year, height, 
              linetype = Month, 
              group = Month,
              color = Month)) +
  geom_line() + 
  facet_grid(. ~ site) + 
  labs(x = "", y = "Height (cm)", title="Monthly Average Vegetation Heights") + 
  theme_bw() + 
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90)) +
  scale_color_manual(values = month_col)

g_monthly
```



```{r robel_yearly, dependson="robel_data"}
s_yearly <- d %>%
  group_by(year, site) %>%
  summarize(height = mean(height))
```

```{r robel_yearly_table, dependson="robel_yearly"}
tab_yearly <- s_yearly %>% 
  spread(year, height) %>%
  xtable(
    align = "ll|rrrr",
    caption = "Yearly average vegetation height (cm) from 2016 through 2019.",
    digits = 1) %>%
  print(
    # file = "include/robel_yearly.tex",
    caption.placement = "top",
    include.rownames = FALSE,
    comment = FALSE)
```

```{r robel_yearly_plot, dependson=c("robel_yearly","palette"),fig.height=4,fig.cap="Yearly average vegetation height (cm) from 2016 through 2019."}
g_yearly <- ggplot(s_yearly, aes(year, height, color = site)) +
  geom_line() + 
  # facet_grid(site ~ .) + 
  labs(x = "", 
       y = "Height (cm)",
       title = "Yearly Average Vegetation Heights") + 
  scale_color_manual(values = site_color) +
  theme_bw() +
  theme(legend.position = "bottom") 

g_yearly
```



```{r robel_write_plots, dependson=c("robel_monthly_plot","robel_yearly_plot")}
ggsave(plot = g_monthly,
       filename = "include/robel_monthly.png")

ggsave(plot = g_yearly,
       filename = "include/robel_yearly.png",
       width = 6, height = 4)
```




\clearpage

\lhead{Daubenmire Survey}

```{r daubenmire_data, dependson="sites"}
d <- cover %>% 
  filter(siteID %in% sites) %>%
  select(siteID, year, month, section, class, percentage) %>%
  rename(site = siteID) %>%
  mutate(month = recode(month, `6` = "June", `7` = "July", `8` = "August"),
         month = factor(month, levels = c("June","July","August")),
         
         site = recode(site, 
                         byd1 = "Boyd 1", 
                         byd2 = "Boyd 2",
                         cra1 = "Crawfordsville",
                         uth3 = "Uthe 3")) %>%
  filter(class %in% c("bare_ground","csg","forbs","milkweed","wsg","woody_species"))
```


```{r daubenmire_yearly, dependson="daubenmire_data"}
s <- d %>%
  group_by(year, site, class) %>%
  summarize(percentage = mean(percentage)) %>%
  ungroup() %>%
  mutate(class = recode(class,
                        bare_ground   = "Bare ground",
                        csg           = "Cool season grass",
                        wsg           = "Warm season grass",
                        milkweed      = "Milkweed",
                        woody_species = "Woody plants",
                        forbs         = "Forbs"),
         class = factor(class, 
                        levels = c("Forbs",
                                   "Milkweed",
                                   "Warm season grass",
                                   "Cool season grass",
                                   "Woody plants",
                                   "Bare ground")))
```


```{r daubenmire_yearly_table, dependson="daubenmire_yearly"}
# ss <- s %>%
#   # Create table by ordering columns by class and then year
#   arrange(site, class, year) %>%
#   mutate(column = factor(paste(class, year, sep="@"),
#                          levels = unique(paste(class, year, sep="@")))) %>%
#   select(site, column, percentage) %>%
#   tidyr::spread(column, percentage, fill=NA) 

ss <- s %>%
  unite("site_year", site, year, sep="@") %>%
  spread(site_year, percentage, fill = NA) 

# Fix column names and create additional row
nc <- ncol(ss)
tmp <- data.frame(nms = names(ss)[-1]) %>%
  tidyr::separate(nms, into=c("row1", "row2"), sep="@")
names(ss)[-1] <- tmp$row2
new_row <- paste(" & \\multicolumn{4}{c|}{",unique(tmp$row1),"}", 
                 collapse="")
new_row <- gsub("_", " ", new_row)
new_row <- paste(new_row, "\\\\", collapse=" ")

# Write table to file
tab <- ss %>%
  xtable(
    digits = 0,
    align = paste("rl|",paste(rep("rrrr|",floor(nc/4)),collapse=""),sep="",collapse=""),
    caption="Yearly average percent cover of forbs, milkweed, warm season grasses, cool season grasses, woody species, and bare ground from 2016 – 2019.",
    label = "t:daubenmire") %>%
  print(
    # file = "include/daubenmire.tex",
    include.rownames = FALSE, 
    # NA.string="na",
    add.to.row = list(pos = list(-1), 
                      command = new_row),
    caption.placement = "top",
    size="\\small",
    # floating.environment = "sidewaystable",
    hline.after = c(-1,0,6),
    comment = FALSE
    ) 
```


```{r daubenmire_yearly_plot, dependson=c("daubenmire_yearly","palette"),fig.cap="Yearly average percent cover of forbs, milkweed, warm season grasses, cool season grasses, woody species, and bare ground from 2016 – 2019."}
g_yearly <- ggplot(s, aes(year, percentage, color=class, linetype = class)) +
  geom_line() + 
  facet_grid(. ~ site, scales = "free_y") +
  labs(x = "Year", y = "Average Cover", title = "Yearly Average Cover by Class") +
  scale_color_manual(values = class_col) +
  scale_linetype_manual(values = class_linetype) +
  theme_bw() + 
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle=90))

g_yearly
```


```{r daubenmire_yearly_cumulative_plot, dependson=c("daubenmire_yearly","palette"), fig.height=8, fig.cap="Trends in yearly cumulative percent cover by vegetative class and bare soil from 2016 through 2019 (based on results for Daubenmire surveys; see Table 2 and Figure 3). "}
g_yearly_by_class <- ggplot(s, aes(year, percentage,
                   fill = class, 
                   # linetype = class, 
                   group = class)) +
  geom_area(color=NA) + 
  facet_grid(site ~ .) +
  labs(x = "Year", y = "Average Cover", title = "Cumulative Yearly Average Cover by Class") +
  scale_fill_manual(values = class_col) +
  theme_bw() +
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle=90))

g_yearly_by_class
```



```{r daubenmire_write_plots, dependson=c("daubenmire_yearly_plot","daubenmire_yearly_cumulative_plot")}
ggsave(filename = "include/daubenmire_yearly.png",
       plot = g_yearly,
       width = 6, 
       height = 4)

ggsave(filename = "include/daubenmire_yearly_cumulative.png",
       plot = g_yearly_by_class,
       width = 6, 
       height = 6)
```


\clearpage

\lhead{Nectar Plant Survey}

```{r nectar_data, dependson="sites"}
d <- ISUmonarch::nectar %>% 
  filter(siteID %in% sites) %>%
  select(siteID, year, month, `Nectar Plant Species`, count) %>%
  rename(site = siteID) %>%
  mutate(month = recode(month, `6` = "June", `7` = "July", `8` = "August"),
         month = factor(month, levels = c("June","July","August")),
         
         site = recode(site, 
                       byd1 = "Boyd 1", 
                       byd2 = "Boyd 2",
                       cra1 = "Crawfordsville",
                       uth3 = "Uthe 3")) %>%
  
  rename(common_name = `Nectar Plant Species`) %>%
  left_join(ISUmonarch::species, by="common_name") %>%
  rename(native = native_introduced_both) %>%
  mutate(native = recode(native, 
                         native     = "Native (extant)",
                         both       = "Introduced/weed",
                         introduced = "Introduced/weed"),
         native = ifelse(planted_non_planted == "planted",
                         "Native (planted)", native),
         
         native = ifelse(common_name == "marestail",
                         "Introduced/weed", native))
```


```{r nectar_monthly_data, dependson="nectar_data"}
s1 <- d %>% 
  group_by(year, site, month) %>%
  summarize(total = mean(count)) %>%
  mutate(native = "Combined",
         total = ifelse(site == "Crawfordsville", total/.7, total))

s2 <- d %>% 
  mutate(native = recode(native, 
                         `Native (planted)` = "Native",
                         `Native (extant)`  = "Native",
                         `Introduced/weed`  = "Introduced")) %>%
  group_by(year, site, month, native) %>%
  summarize(total = mean(count)) %>%
  mutate(total = ifelse(site == "Crawfordsville", total/.7, total)) %>%

  # Hack to add appropriate zeros
  bind_rows(tibble(site = rep(c("Boyd 1","Boyd 2"), each = 4),
                   year = rep(c(2016,2016,2016,2017),2),
                   native = rep("Native",8),
                   month  = rep(c("June","July","August","June"),2),
                   total  = rep(0,8)) %>%
              mutate(month = factor(month, levels=c("June","July","August"))))
  

s_both <- bind_rows(s1,s2) %>%
  mutate(native = factor(native, levels = c("Combined",
                                            "Native",
                                            "Introduced")))
```


```{r nectar_monthly_plot, dependson="nectar_monthly_data",fig.cap="Plots of monthly average native forbs, extant native forbs, introduced/weed species, and combined (native and introduced/weed) nectar plant inflorescence density by year for each site."}
g <- ggplot(s_both, aes(year, total, 
              linetype = month, group = month, color = month)) +
  geom_line() + 
  facet_grid(native ~ site, scales="free_y") + 
  labs(x = "Year", y = "Average Inflorescence (count/100m2)", 
       title = "Average Monthly Inflorescence",
       linetype = "Month", color = "Month") +
  # scale_y_log10() +
  scale_color_manual(values = month_col) + 
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=90))

g
```



```{r, nectar_write_plots, dependson="nectar_monthly_plot"}
ggsave(file = "include/nectar_monthly.png",
       plot = g,
       width = 6, 
       height = 4)
```



```{r, nectar_by_species, dependson="nectar_data"}
s <- d %>% 
  # filter(`Nectar Plant Species` != "white clover") %>%
  group_by(year, site, month, common_name, native) %>%
  summarize(total = sum(count)) %>%
  ungroup()
```  


```{r nectar_ratio, dependson="nectar_by_species", eval=TRUE}
# ggplot(s, aes(year, total, 
#               color = common_name,
#               linetype = native,
#               group = common_name)) +
#   geom_line() + 
#   facet_grid(site ~ month) + 
#   labs(x = "Year", y = "Inflorescence", linetype = "Species") +
#   scale_y_log10() + 
#   theme_bw() + 
#   theme(legend.position = "bottom")

ss <- s %>%
  group_by(year, site, common_name, native) %>%
  summarize(total = sum(total)) %>%
  spread(year, total, fill = 0) %>%
  mutate(log_ratio = log10(`2019`+1) - log10(`2018`+1)) %>% 
  # arrange(native, log_ratio, common_name, site) %>%
  select(site, common_name, native, log_ratio) %>%
  spread(site, log_ratio, fill=NA) %>%
  
  # Manually filter species with only 1 site with data and
  # ratio is close to zero
  filter(!(common_name %in% c("blue wild indigo","canada goldenrod",
                              "common evening primrose","prostrate vervain",
                              "hawkweed","smartweed","common milkweed")))

ss %>% write_csv("include/nectar_ratio.csv")
```


```{r, nectar_ratio_by_mean_ratio, dependson="nectar_ratio", eval=TRUE}
ss %>%
  arrange(
    -rowMeans(cbind(`Boyd 1`,`Boyd 2`,Crawfordsville,`Uthe 3`), na.rm=TRUE),
    common_name) %>%
  select(native, common_name, everything()) %>%
  rename(`Common name` = common_name,
         `Native status` = native) %>%
  
  xtable(
    caption = "Logarithm of the ratio of inflorescence counts (+1) from 2019  to 2018 arranged by average across sites,
    thus negative values indicate a reduction while positive values indicate an increase. Missing values had no observations at that site for either 2018 or 2019.",
    align = "lll|rrrr",
    digits = 1
  ) %>%
  
  print(
    include.rownames = FALSE,
    caption.placement = "top",
    comment = FALSE
  )
```

```{r, nectar_ratio_by_native, dependson="nectar_ratio", eval=TRUE}
n_native  = sum(grepl("Native",  ss$native))
n_planted = sum(grepl("planted", ss$native))

ss %>%
  mutate(native = factor(native, levels = c("Native (planted)",
                                            "Native (extant)",
                                            "Introduced/weed"))) %>%
  arrange(
    native,
    -rowMeans(cbind(`Boyd 1`,`Boyd 2`,Crawfordsville,`Uthe 3`), na.rm=TRUE),
    common_name) %>%
  select(-native) %>%
  rename(`Common name` = common_name) %>%
  
  xtable(
    caption = "Logarithm of the ratio of inflorescence counts (+1) from 2019 over 2018 arranged by mean ratio across sites within each native grouping: native above double line and planted above single line. Negative values indicate a reduction while positive values indicate an increase. Missing values had no observations at that site for either 2018 or 2019.",
    align = "ll|rrrr",
    digits = 1
  ) %>%
  
  print(
    include.rownames = FALSE,
    caption.placement = "top",
    hline.after = c(-1,0,n_planted,n_native,n_native,nrow(ss)),
    comment = FALSE
  )
```




```{r, nectar_write_table, dependson="nectar_by_species"}
ss <- s %>%
  group_by(year, site, common_name, native) %>%
  summarize(density = mean(total)) %>%
  mutate(native = factor(native, levels=c("Native (planted)","Native (extant)",
                                          "Introduced/weed"))) %>%
  
  # cra1 has a 70m transect, so adjust to 100m density
  mutate(density = ifelse(site == "Crawfordsville", density/.7, density)) %>%
  unite("site_year", site, year, sep="@") %>%
  spread(site_year, density, fill = NA) %>%
  arrange(native, common_name) %>%
  rename(`Plant name` = "common_name")

n_native  = sum(grepl("Native",  ss$native))
n_planted = sum(grepl("planted", ss$native))
ss$native <- NULL

# Fix column names and create additional row
nc <- ncol(ss)
tmp <- data.frame(nms = names(ss)[-1]) %>%
  tidyr::separate(nms, into=c("row1", "row2"), sep="@")
names(ss)[-1] <- tmp$row2
new_row <- paste(" & \\multicolumn{4}{c|}{",unique(tmp$row1),"}", 
                 collapse="")
new_row <- gsub("_", " ", new_row)
new_row <- paste(new_row, "\\\\", collapse=" ")

tab <- ss %>%
  xtable(
    digits = 0,
    align = paste("rl|",paste(rep("rrrr|",floor(nc/4)),collapse=""),sep="",collapse=""),
    caption="Average inflourescence (count/100m2) across all rounds by plant classification: native (planted or extant) above double line, planted above single line, and introduced/weed below double line.",
    label = "t:nectar") %>%
  print(
    # file = "include/nectar_yearly.tex",
    include.rownames = FALSE, 
    # NA.string="na",
    add.to.row = list(pos = list(-1), 
                      command = new_row),
    caption.placement = "top",
    size="\\small",
    # floating.environment = "sidewaystable",
    hline.after = c(-1,0,n_planted,n_native,n_native,nrow(ss)),
    comment = FALSE
  ) 
```



```{r nectar_heatmap, dependson="nectar_by_species",fig.height=8,fig.cap="Heat map of average nectar plant inflorescence density; species sorted by average presence."}
# Determine sort order 
abundance <- s %>%
  group_by(common_name) %>%
  summarize(total = sum(total)) %>%
  arrange(total)

ss <- s %>%
  mutate(common_name = factor(common_name,
                              levels = abundance$common_name))

g <- ggplot(ss %>% 
              mutate(native = factor(native, 
                                     levels=c("Native (planted)",
                                              "Native (extant)",
                                              "Introduced/weed"))), 
            aes(year, common_name, fill = total)) +
  geom_tile() + 
  # scale_y_discrete(limits = rev(levels(as.factor(s$common_name)))) +
  facet_grid(native ~ site, scales="free_y", space="free_y") + 
  scale_fill_gradient(low = "cornsilk", high = "darkgreen", trans = "log") +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle=90),
        axis.text.y = element_text(hjust=0)) +
  labs(x = "", y = "") 

g
```

```{r, nectar_write_heatmap, dependson="nectar_heatmap"}
ggsave(file = "include/nectar_heatmap.png",
       plot = g,
       width = 6, 
       height = 8)
```


\clearpage

\lhead{Monarch Survey}

```{r monarch_data, dependson="sites"}
d <- monarch %>% 
  filter(siteID %in% sites,
         type != "palmer amaranth") %>%
  rename(site = siteID) %>%
  mutate(month = recode(month, `6` = "June", `7` = "July", `8` = "August"),
         month = factor(month, levels = c("June","July","August")),
         
         site = recode(site, 
                         byd1 = "Boyd 1", 
                         byd2 = "Boyd 2",
                         cra1 = "Crawfordsville",
                         uth3 = "Uthe 3")) %>% 
  
  group_by(year, site, type, milkweed) %>%
  summarize(total = sum(count)) %>%
  ungroup() %>%
  
  # Create total columns
  mutate(type = recode(type, extra = "total", instar = "larvae")) %>%
  unite("type_milkweed", type, milkweed) %>%
  spread(type_milkweed, total, fill = 0) %>%
  mutate(total_NA = survey_NA + total_NA,
         eggs_NA   = eggs_NA   + eggs_common   + eggs_butterfly   + eggs_swamp,
         ramets_NA = ramets_NA + ramets_common + ramets_butterfly + ramets_swamp,
         larvae_NA = larvae_NA + larvae_common + larvae_butterfly + larvae_swamp) %>%
  gather("type_milkweed", "count", -year, -site) %>%
  separate(type_milkweed, c("type","milkweed"), sep="_") %>%
  
  mutate(
    milkweed = ifelse(type == "survey", "survey", milkweed),
    milkweed = ifelse(type == "total", "", milkweed),
    # milkweed = tools::toTitleCase(milkweed),
    milkweed = factor(milkweed, 
                      levels = c("butterfly","common","swamp","survey","total")),
    
    type = recode(type, survey = "adults", total = "adults"),
    type = tools::toTitleCase(type)) %>%
  unite("Monarch", type, milkweed, sep=", ") %>%
  mutate(
    Monarch = gsub(", NA", ", total", Monarch),
    Monarch = factor(Monarch, 
                     levels = c("Adults, survey", "Adults, total",
                                "Eggs, butterfly", "Eggs, common", "Eggs, swamp", "Eggs, total",
                                "Larvae, butterfly", "Larvae, common", "Larvae, swamp", "Larvae, total",
                                "Ramets, butterfly", "Ramets, common", "Ramets, swamp", "Ramets, total"))) 
```

```{r monarch_table, dependson="monarch_data"}
ss <- d %>%
  unite("site_year", site, year, sep="@") %>%
  spread(site_year, count, fill = NA) 


nc <- ncol(ss)
tmp <- data.frame(nms = names(ss)[-1]) %>%
  tidyr::separate(nms, into=c("row1", "row2"), sep="@")
names(ss)[-1] <- tmp$row2
new_row <- paste(" & \\multicolumn{4}{c|}{",unique(tmp$row1),"}", 
                 collapse="")
new_row <- gsub("_", " ", new_row)
new_row <- paste(new_row, "\\\\", collapse=" ")


ss %>%
  # spread(site, count) %>%
  # arrange(Monarch, year) %>% 
  xtable(
    digits = 0,
    align = paste("rl|",paste(rep("rrrr|",floor(nc/4)),collapse=""),sep="",collapse=""),
caption = "Yearly observed monarch eggs, larvae (by milkweed species), adults during the pollard walk, total adults during a site visit and total number of milkweed ramets (butterfly, common and swamp) and combined.") %>%
  print(
    # file = "monarch.tex",
    include.rownames = FALSE,
    caption.placement = "top",
    add.to.row = list(pos = list(-1), command = new_row),
    hline.after = c(-1,0,2,6,10,14),
    comment = FALSE)
```

```{r monarch_plot, dependson="monarch_data",fig.cap="Yearly observed monarch eggs, larvae, and adults during a site visit and total number of milkweed ramets (butterfly, common and swamp combined)."}
g <- ggplot(d %>%
              mutate(Monarch = sub(", total","",Monarch)) %>%
              filter(Monarch %in% c("Adults","Eggs","Larvae","Ramets")), 
            aes(year, count)) +
  geom_line() + 
  facet_grid(Monarch ~ site, scales="free_y") + 
  labs(x = "Year", y = "Count",
       title = "Yearly Monarch Adults, Eggs, Larvae, and Milkweed Ramets") +
  # scale_y_log10() + 
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=90))
g
```

```{r write_monarch_plots, dependson="monarch_plot"}
ggsave(file = "include/monarch_yearly.png",
       plot = g,
       width = 6, 
       height = 4)
```



\clearpage

\lhead{Bee Survey}

```{r bee_data, dependson="sites"}
d <- ISUmonarch::bee %>% 
  ungroup() %>%
  left_join(ISUmonarch::transect %>% select(transectID, siteID), 
            by = "transectID") %>%
  select(-transectID) %>%
  filter(siteID %in% sites) %>%
  rename(site = siteID) %>%
  mutate(month = recode(month, `6` = "June", `7` = "July", `8` = "August"),
         month = factor(month, levels = c("June","July","August")),
         
         site = recode(site, 
                         byd1 = "Boyd 1", 
                         byd2 = "Boyd 2",
                         cra1 = "Crawfordsville",
                         uth3 = "Uthe 3")) %>% 
  
  group_by(year, site, `Bee Species`) %>%
  summarize(total = sum(count)) %>%
  ungroup() %>%
  complete(year, site, `Bee Species`, fill = list(total = 0)) %>%
  rename(`Bee type` = `Bee Species`) %>%
  mutate(`Bee type` = sub(" bee"," ",`Bee type`))
```

```{r bee_table, dependson="bee_data"}
ss <- d %>%
  unite("site_year", site, year, sep="@") %>%
  spread(site_year, total, fill = NA) 


nc <- ncol(ss)
tmp <- data.frame(nms = names(ss)[-1]) %>%
  tidyr::separate(nms, into=c("row1", "row2"), sep="@")
names(ss)[-1] <- tmp$row2
new_row <- paste(" & \\multicolumn{4}{c|}{",unique(tmp$row1),"}", 
                 collapse="")
new_row <- gsub("_", " ", new_row)
new_row <- paste(new_row, "\\\\", collapse=" ")


ss %>%
  xtable(
    digits = 0,
    align = paste("rl|",paste(rep("rrrr|",floor(nc/4)),collapse=""),sep="",collapse=""),
    caption = "Yearly count of bumble bees, honey bees, and solitary bees by site.") %>%
  print(
    # file = "include/bee_yearly.tex",
    add.to.row = list(pos = list(-1), command = new_row),
    include.rownames = FALSE,
    caption.placement = "top",
    comment = FALSE)
```

```{r bee_plot, dependson="bee_data",fig.cap="Total count of bumble bees, honey bees, and solitary bees by site and year."}
g <- ggplot(d, aes(year, total)) +
  geom_line() + 
  # geom_point() + 
  facet_grid(`Bee type` ~ site, scales="free_y") + 
  labs(x = "Year", y = "Count",
       title = "Yearly Bee Counts") +
  # scale_y_log10() + 
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=90))

g
```

```{r write_bee_plot, dependson="bee_plot"}
ggsave(file = "include/bee_yearly.png",
       plot = g,
       width = 6, 
       height = 4)
```


```{r bee_plants_data, dependson="sites"}
d <- ISUmonarch::bee_plants %>% 
  ungroup() %>%
  left_join(ISUmonarch::transect %>% select(transectID, siteID),
            by = "transectID") %>%
  select(-transectID) %>%
  filter(siteID %in% sites,
         `Nectar Plant Species` != "unknown") %>%
  rename(site = siteID) %>%
  mutate(
    `Nectar Plant Species` = recode(`Nectar Plant Species`,
                                    `yellow cone flower` = "yellow coneflower"),
    
    month = recode(month, `6` = "June", `7` = "July", `8` = "August"),
    month = factor(month, levels = c("June","July","August")),
    
    site = recode(site, 
                  byd1 = "Boyd 1", 
                  byd2 = "Boyd 2",
                  cra1 = "Crawfordsville",
                  uth3 = "Uthe 3")) %>%
  
  group_by(year, site, `Nectar Plant Species`, `Bee Species`) %>%
  summarize(count = sum(count)) %>%
  ungroup() %>%
  
  rename(common_name = `Nectar Plant Species`) %>%
  left_join(ISUmonarch::species, by="common_name") %>%
  rename(native = native_introduced_both) %>%
  mutate(native = recode(native, 
                         native     = "Native (extant)",
                         both       = "Introduced/weed",
                         introduced = "Introduced/weed"),
         native = ifelse(planted_non_planted == "planted",
                         "Native (planted)", native),
         
         native = ifelse(common_name == "marestail",
                         "Introduced/weed", native))
```


```{r bee_plant_heatmap, dependson="bee_plants_data",fig.height=4,fig.cap="Plant usage by bees by classification: native (planted), native (extant), and introduced/weed."}
# Determine sort order 
abundance <- d %>%
  group_by(common_name) %>%
  summarize(total = sum(count)) %>%
  arrange(total)

ss <- d %>%
  mutate(common_name = factor(common_name,
                              levels = abundance$common_name))

g <- ggplot(ss %>% 
              mutate(
                native = recode(native, 
                                `Native (extant)` = "Native",
                                `Introduced/weed` = "Introduced"),
                native = factor(native, 
                                     levels=c("Native (planted)",
                                              "Native",
                                              "Introduced"))), 
            aes(year, common_name, fill = count)) +
  geom_tile() + 
  # scale_y_discrete(limits = rev(levels(as.factor(s$common_name)))) +
  facet_grid(native ~ site, scales="free_y", space="free_y") + 
  scale_fill_gradient(low = "cornsilk", high = "darkgreen", trans = "log") +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle=90),
        axis.text.y = element_text(hjust=0)) +
  labs(x = "", y = "") 

g
```

```{r write_bee_plant_heatmap, dependson="bee_plant_heatmap"}
ggsave(file = "include/bee_plant_heatmap.png",
       plot = g,
       width = 6, 
       height = 4)
```



```{r bee_plant_table, dependson="bee_plants_data", eval=TRUE}
ss <- d %>%
  group_by(year, site, common_name, native, `Bee Species`) %>%
  summarize(total = sum(count)) %>%
  ungroup %>%
  tidyr::complete(nesting(common_name, native), year, site, `Bee Species`, 
                  fill = list(total=NA)) %>%
  mutate(native = factor(native, 
                         levels=c("Native (planted)",
                                  "Native (extant)",
                                  "Introduced/weed")),
         `Bee Species` = gsub(" bee","",`Bee Species`)) %>%
  unite("site_year", site, year, sep="@") %>%
  spread(site_year, total, fill = NA) %>%
  
  # Remove rows that are entirely NA
  filter_at(vars(-native, -`Bee Species`, -common_name), any_vars(!is.na(.))) %>%
  
  arrange(native, `Bee Species`, common_name) %>%
  select(`Bee Species`, native, common_name, everything()) %>%
  rename(`Plant name` = "common_name",
         `Bee type` = "Bee Species") 

n_native  = sum(grepl("Native",  ss$native))
n_planted = sum(grepl("planted", ss$native))
ss$native <- NULL

# Fix column names and create additional row
nc <- ncol(ss)
tmp <- data.frame(nms = names(ss)[-c(1:2)]) %>%
  tidyr::separate(nms, into=c("row1", "row2"), sep="@")
names(ss)[-c(1:2)] <- tmp$row2
new_row <- paste(" & \\multicolumn{4}{c|}{",unique(tmp$row1),"}", 
                 collapse="")
new_row <- gsub("_", " ", new_row)
new_row <- paste("&", new_row, "\\\\", collapse=" ")

tab <- ss %>%
  xtable(
    digits = 0,
    align = paste("rll|",paste(rep("rrrr|",floor(nc/4)),collapse=""),sep="",collapse=""),
    caption="Bee plant usage by bee type and plant classification: native (planted or extant) above double line, planted above single line, and introduced/weed below double line.",
    label = "t:bee_plant") %>%
  print(
    # file = "include/nectar_yearly.tex",
    include.rownames = FALSE, 
    # NA.string="na",
    add.to.row = list(pos = list(-1),
                      command = new_row),
    caption.placement = "top",
    size="\\small",
    # floating.environment = "sidewaystable",
    hline.after = c(-1,0,n_planted,n_native,n_native,nrow(ss)),
    comment = FALSE
  ) 
```

