---
title: "ISU Monarch Data Summary for NCIG"
author: "Jarad Niemi and Seth Appelgate"
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{rotating}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output: 
  pdf_document:
    fig_caption: TRUE
---

```{r setup, purl=FALSE, echo=FALSE}
library("knitr")
opts_chunk$set(echo    = FALSE, 
               results = 'asis',
               message = FALSE)
```

```{r packages}
suppressWarnings(library("tidyverse"))
library("ISUmonarch")
library("xtable")
options(xtable.comment = FALSE)
```

\setlength{\tabcolsep}{3pt}


```{r sites}
sites = as.character(unique(transect$transectID))
sites18 = as.character(unique(sites[!(sites %in% c("tuth1a", "tuth2a", "tsie1a"))]))
sites = as.character(unique(sites[!(sites %in% c("tuth1a", "tuth2a", "tsie1a", "tfis1a"))]))
```


<!-- Bee -->
```{r bee, warning=FALSE, message=FALSE}
bee %>% 
  rename(common_name = `Nectar Plant Species`) %>%
  left_join(species, by="common_name") %>%
  complete(`Bee Species`, transectID, year, round, fill = list(count = 0)) %>%
  group_by(transectID, year, round, `Bee Species`, native_introduced_both) %>%
  summarize(count = sum(count)) %>% 
  group_by(transectID, year, `Bee Species`, native_introduced_both) %>% 
  summarize(count = mean(count)) %>% 
  rename(`Native Status` = native_introduced_both) %>%
  ungroup() %>%
  mutate(`Bee Species` = sub(" bee", "", `Bee Species`)) %>%
  filter(!(is.na(`Native Status`) & count==0)) %>%
  filter(!(is.na(`Native Status`))) %>%
  spread(transectID, count, fill=NA)  %>%
    
    xtable(digits = c(0,0,0,0, rep(0,6)),
           caption=paste("Bee species: mean count across all surveys"),
           label = paste("t:bee",sep="")) %>%
    print(include.rownames = FALSE, 
          NA.string="-", 
          # rotate.colnames = TRUE,
          table.placement = "p",
          caption.placement = "top",
          size="\\small")
          # ,
          # floating.environment = "sidewaystable") 
```


```{r bee_18, warning=FALSE, message=FALSE}
bee %>% 
  # rename(common_name = `Nectar Plant Species`) %>%
  # left_join(species, by="common_name") %>%
  filter(year == 2018) %>%
  complete(`Bee Species`, transectID, round, fill = list(count = 0)) %>%
  group_by(transectID, year, `Bee Species`, `Nectar Plant Species`) %>% 
  summarize(count = mean(count)) %>% 
  ungroup() %>%
  mutate(`Bee Species` = sub(" bee", "", `Bee Species`)) %>%
  filter(!(is.na(`Nectar Plant Species`) & count==0)) %>%
  spread(transectID, count, fill=NA) %>% 
  as.data.frame %>%
    
    xtable(digits = c(0,0,0,0, rep(2,6)),
           caption=paste("2018 bee species: mean count across all surveys"),
           label = paste("t:bee18",sep="")) %>%
    print(include.rownames = FALSE, 
          NA.string="-", 
          # rotate.colnames = TRUE,
          table.placement = "p",
          caption.placement = "top",
          size="\\small")
          # ,
          # floating.environment = "sidewaystable") 
```






\newpage
```{r bee_plot, warning=FALSE, message=FALSE, fig.height=5, fig.width=9, fig.cap="This is a visual representation of Table \ref{t:bee}."}
bee %>% 
  rename(common_name = `Nectar Plant Species`) %>%
  left_join(species, by="common_name") %>%
  complete(`Bee Species`, transectID, year, round, fill = list(count = 0)) %>%
  group_by(transectID, year, round, `Bee Species`, native_introduced_both) %>%
  summarize(count = sum(count)) %>% 
  group_by(transectID, year, `Bee Species`, native_introduced_both) %>% 
  summarize(count = mean(count)) %>% 
  rename(`Native Status` = native_introduced_both) %>%
  ungroup() %>%
  mutate(`Bee Species` = sub(" bee", "", `Bee Species`)) %>%
  filter(!(is.na(`Native Status`) & count==0)) %>%
  filter(!(is.na(`Native Status`))) %>%
  
  ggplot(., aes(x=year, y=count, color=`Native Status`)) + 
    geom_point() + 
    facet_grid(`Bee Species`~transectID) + 
    theme_bw() + 
    # scale_y_log10() + 
    labs(x="Year", y="Mean Count", color="Native Status")
```




```{r bee_overall, warning=FALSE, message=FALSE}
bee %>% 
  group_by(year) %>%
  summarize(count = sum(count)) %>% 
  spread(year, count, fill=NA)  %>%
    
    xtable(digits = c(0,0,0,0),
           caption=paste("Bee species: yearly counts across all species"),
           label = paste("t:bee",sep="")) %>%
    print(include.rownames = FALSE, 
          NA.string="-", 
          table.placement = "p",
          caption.placement = "top")
```


```{r bee_by_year, warning=FALSE, message=FALSE}
bee %>% 
  group_by(year, `Bee Species`) %>%
  summarize(count = sum(count)) %>% 
  ungroup() %>%
  mutate(`Bee Species` = sub(" bee", "", `Bee Species`)) %>%
  spread(year, count, fill=NA)  %>%
    
    xtable(digits = c(0,0,0,0,0),
           caption=paste("Bee species: yearly counts broken down by species"),
           label = paste("t:bee",sep="")) %>%
    print(include.rownames = FALSE, 
          NA.string="-", 
          table.placement = "p",
          caption.placement = "top")

```


